const http = require("http");
const fs = require("fs");
const path = require("path");

const PORT = Number(process.env.PORT || 2107);
const DATA_DIR = process.env.DATA_DIR || "/data";
const FRIGATE_HOME = path.join(DATA_DIR, "frigate");
const CONFIG_PATH = path.join(FRIGATE_HOME, "config.toml");
const START_PATH = path.join(FRIGATE_HOME, "start");
const STATE_PATH = path.join(DATA_DIR, "state.json");
const CONTROLLER_LOG_PATH = path.join(DATA_DIR, "controller.log");
const STATIC_DIR = path.join(__dirname, "..", "web");
const TAPROOT_HEIGHT = 709632;

let lastKnownHeight = 0;
let ready = false;

fs.mkdirSync(FRIGATE_HOME, { recursive: true });

function readJson(file, fallback) {
  try {
    return JSON.parse(fs.readFileSync(file, "utf8"));
  } catch (_) {
    return fallback;
  }
}

function writeJson(file, value) {
  fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`);
}

function appendLog(line) {
  const value = line.endsWith("\n") ? line : `${line}\n`;
  fs.appendFileSync(CONTROLLER_LOG_PATH, value);
}

function quoteToml(value) {
  return String(value || "").replace(/\\/g, "\\\\").replace(/"/g, "\\\"");
}

function normalizeConfig(input = {}) {
  return {
    startHeight: Number(input.startHeight || TAPROOT_HEIGHT),
    cacheSize: String(input.cacheSize || "10M"),
    computeBackend: String(input.computeBackend || "AUTO"),
    batchSize: Number(input.batchSize || 300000),
    dbThreads: Number(input.dbThreads || 0),
    memoryLimit: String(input.memoryLimit || ""),
    maxLabels: Number(input.maxLabels || 10),
    maxSubscriptions: Number(input.maxSubscriptions || 100),
    tcpPort: Number(input.tcpPort || process.env.FRIGATE_TCP_PORT || 57001),
    rpcRequestTimeoutSeconds: Number(input.rpcRequestTimeoutSeconds || 60),
    rpcBatchSize: Number(input.rpcBatchSize || 100),
    advertisedHost: String(input.advertisedHost || ""),
    sslListener: String(input.sslListener || ""),
    sslCert: String(input.sslCert || ""),
    sslKey: String(input.sslKey || ""),
    backendElectrumServer: String(input.backendElectrumServer || process.env.ELECTRUM_BACKEND_SERVER || ""),
    zmqSequenceEndpoint: String(input.zmqSequenceEndpoint || process.env.BITCOIN_ZMQ_SEQUENCE_ENDPOINT || ""),
  };
}

function createToml(config) {
  const rpcHost = process.env.BITCOIN_RPC_HOST || "127.0.0.1";
  const rpcPort = process.env.BITCOIN_RPC_PORT || "8332";
  const rpcUser = process.env.BITCOIN_RPC_USER || "";
  const rpcPass = process.env.BITCOIN_RPC_PASS || "";
  const memoryLimitLine = config.memoryLimit ? `memoryLimit = "${quoteToml(config.memoryLimit)}"` : "# memoryLimit = \"\"";
  const dbThreadsLine = config.dbThreads > 0 ? `dbThreads = ${config.dbThreads}` : "# dbThreads = 0";
  const backendLine = config.backendElectrumServer ? `backendElectrumServer = "${quoteToml(config.backendElectrumServer)}"` : "# backendElectrumServer = \"\"";
  const zmqLine = config.zmqSequenceEndpoint ? `zmqSequenceEndpoint = "${quoteToml(config.zmqSequenceEndpoint)}"` : "# zmqSequenceEndpoint = \"\"";
  const advertisedHostLine = config.advertisedHost ? `host = "${quoteToml(config.advertisedHost)}"` : "# host = \"\"";
  const sslLine = config.sslListener ? `ssl = "${quoteToml(config.sslListener)}"` : "# ssl = \"\"";
  const sslCertLine = config.sslCert ? `sslCert = "${quoteToml(config.sslCert)}"` : "# sslCert = \"cert.pem\"";
  const sslKeyLine = config.sslKey ? `sslKey = "${quoteToml(config.sslKey)}"` : "# sslKey = \"key.pem\"";

  return `# Frigate configuration generated by Umbrel\n\n[core]\nconnect = true\nserver = "http://${quoteToml(rpcHost)}:${quoteToml(rpcPort)}"\nauthType = "USERPASS"\nauth = "${quoteToml(rpcUser)}:${quoteToml(rpcPass)}"\ndataDir = "/bitcoin"\n${zmqLine}\nrpcRequestTimeoutSeconds = ${config.rpcRequestTimeoutSeconds}\nrpcBatchSize = ${config.rpcBatchSize}\n\n[index]\nstartHeight = ${config.startHeight}\ncacheSize = "${quoteToml(config.cacheSize)}"\n\n[scan]\nbatchSize = ${config.batchSize}\ncomputeBackend = "${quoteToml(config.computeBackend)}"\n${dbThreadsLine}\n${memoryLimitLine}\nmaxLabels = ${config.maxLabels}\nmaxSubscriptions = ${config.maxSubscriptions}\n\n[server]\n${advertisedHostLine}\ntcp = "tcp://0.0.0.0:${config.tcpPort}"\n${sslLine}\n${sslCertLine}\n${sslKeyLine}\n${backendLine}\n`;
}

function saveConfig(input) {
  const config = normalizeConfig(input);
  fs.mkdirSync(FRIGATE_HOME, { recursive: true });
  fs.writeFileSync(CONFIG_PATH, createToml(config));
  writeJson(STATE_PATH, { configured: true, config, savedAt: new Date().toISOString() });
  return config;
}

function startFrigate() {
  if (!fs.existsSync(CONFIG_PATH)) return;
  fs.writeFileSync(START_PATH, new Date().toISOString());
  appendLog("[controller] Start signal written for Frigate service");
}

function stopFrigate() {
  try {
    fs.unlinkSync(START_PATH);
    appendLog("[controller] Start signal removed. Restart the app from Umbrel to stop a running Frigate process.");
  } catch (_) {}
}

function restartFrigate() {
  startFrigate();
}

function bitcoinRpc(method, params = []) {
  return new Promise((resolve) => {
    const host = process.env.BITCOIN_RPC_HOST;
    const port = Number(process.env.BITCOIN_RPC_PORT || 8332);
    const user = process.env.BITCOIN_RPC_USER || "";
    const pass = process.env.BITCOIN_RPC_PASS || "";
    if (!host) return resolve(null);

    const body = JSON.stringify({ jsonrpc: "1.0", id: "frigate-umbrel", method, params });
    const request = http.request({
      host,
      port,
      method: "POST",
      path: "/",
      timeout: 4000,
      headers: {
        "Content-Type": "application/json",
        "Content-Length": Buffer.byteLength(body),
        Authorization: `Basic ${Buffer.from(`${user}:${pass}`).toString("base64")}`,
      },
    }, (response) => {
      let data = "";
      response.on("data", (chunk) => { data += chunk; });
      response.on("end", () => {
        try {
          resolve(JSON.parse(data).result);
        } catch (_) {
          resolve(null);
        }
      });
    });
    request.on("error", () => resolve(null));
    request.on("timeout", () => request.destroy());
    request.end(body);
  });
}

function tailFile(file, maxBytes = 100000) {
  try {
    const stat = fs.statSync(file);
    const start = Math.max(0, stat.size - maxBytes);
    const fd = fs.openSync(file, "r");
    const buffer = Buffer.alloc(stat.size - start);
    fs.readSync(fd, buffer, 0, buffer.length, start);
    fs.closeSync(fd);
    return buffer.toString("utf8");
  } catch (_) {
    return "";
  }
}

function getFrigateLogPath() {
  const network = process.env.FRIGATE_NETWORK || "mainnet";
  if (network === "mainnet") return path.join(FRIGATE_HOME, "frigate.log");
  return path.join(FRIGATE_HOME, network, "frigate.log");
}

function getHiddenService() {
  try {
    return fs.readFileSync(process.env.FRIGATE_HIDDEN_SERVICE_FILE || "", "utf8").trim();
  } catch (_) {
    return "notyetset.onion";
  }
}

function updateStatusFromLogs() {
  const logs = tailFile(getFrigateLogPath(), 200000);
  ready = logs.includes("Electrum server listening");
  const matches = [...logs.matchAll(/(?:height|block)\D+(\d{6,})/gi)];
  for (const match of matches) lastKnownHeight = Math.max(lastKnownHeight, Number(match[1]));
}

async function getStatus() {
  updateStatusFromLogs();
  const state = readJson(STATE_PATH, { configured: false, config: normalizeConfig() });
  const tipHeight = await bitcoinRpc("getblockcount");
  const indexInfo = await bitcoinRpc("getindexinfo");
  const startHeight = Number(state.config?.startHeight || TAPROOT_HEIGHT);
  const currentHeight = Math.max(lastKnownHeight, startHeight);
  const tip = Number(tipHeight || 0);
  const progress = tip > startHeight ? Math.min(100, Math.max(0, ((currentHeight - startHeight) / (tip - startHeight)) * 100)) : 0;

  return {
    configured: Boolean(state.configured && fs.existsSync(CONFIG_PATH)),
    running: fs.existsSync(START_PATH),
    ready,
    progress: ready ? 100 : Number(progress.toFixed(2)),
    startHeight,
    currentHeight,
    tipHeight: tip || null,
    txindex: indexInfo?.txindex ? Boolean(indexInfo.txindex.synced) : null,
    localHost: process.env.DEVICE_DOMAIN_NAME || "umbrel.local",
    tcpPort: Number(state.config?.tcpPort || process.env.FRIGATE_TCP_PORT || 57001),
    hiddenService: getHiddenService(),
    network: process.env.FRIGATE_NETWORK || "mainnet",
    config: state.config || normalizeConfig(),
  };
}

function sendJson(response, status, value) {
  response.writeHead(status, { "Content-Type": "application/json" });
  response.end(JSON.stringify(value));
}

function readBody(request) {
  return new Promise((resolve) => {
    let body = "";
    request.on("data", (chunk) => { body += chunk; });
    request.on("end", () => {
      try {
        resolve(JSON.parse(body || "{}"));
      } catch (_) {
        resolve({});
      }
    });
  });
}

function serveStatic(request, response) {
  const requestPath = request.url === "/" ? "/index.html" : request.url.split("?")[0];
  const safePath = path.normalize(requestPath).replace(/^\.\.(\/|\\|$)/, "");
  const filePath = path.join(STATIC_DIR, safePath);
  const contentTypes = { ".html": "text/html", ".css": "text/css", ".js": "application/javascript", ".svg": "image/svg+xml" };
  fs.readFile(filePath, (error, data) => {
    if (error) {
      response.writeHead(404);
      response.end("Not found");
      return;
    }
    response.writeHead(200, { "Content-Type": contentTypes[path.extname(filePath)] || "application/octet-stream" });
    response.end(data);
  });
}

const server = http.createServer(async (request, response) => {
  if (request.url === "/api/status") return sendJson(response, 200, await getStatus());
  if (request.url === "/api/config" && request.method === "GET") return sendJson(response, 200, readJson(STATE_PATH, { configured: false, config: normalizeConfig() }));
  if (request.url === "/api/config" && request.method === "POST") {
    const body = await readBody(request);
    const config = saveConfig(body);
    restartFrigate();
    return sendJson(response, 200, { configured: true, config });
  }
  if (request.url === "/api/start" && request.method === "POST") {
    startFrigate();
    return sendJson(response, 200, { running: fs.existsSync(START_PATH) });
  }
  if (request.url === "/api/stop" && request.method === "POST") {
    stopFrigate();
    return sendJson(response, 200, { stopping: true });
  }
  if (request.url === "/api/logs") {
    const logs = [tailFile(CONTROLLER_LOG_PATH), tailFile(getFrigateLogPath())].filter(Boolean).join("\n");
    return sendJson(response, 200, { logs });
  }
  serveStatic(request, response);
});

server.listen(PORT, "0.0.0.0", () => {
  appendLog(`[controller] UI listening on 0.0.0.0:${PORT}`);
});

process.on("SIGTERM", () => {
  process.exit(0);
});
