version: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: server
      APP_PORT: 8080

  server:
    build: .
    container_name: albercoin-store-umbrel-tunnel
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}:/data
    environment:
      LISTEN_ADDR: ":8080"
      DATA_DIR: "/data"
      UI_AUTH_USER: ""
      UI_AUTH_PASS: ""
      WG_INTERFACE: "umbreltun"
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
      - NET_RAW
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    devices:
      - "/dev/net/tun:/dev/net/tun"
