version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_ALBERCOIN_STORE_FRIGATE_IP
      APP_PROTOCOL: http
      APP_PORT: 2107

  app:
    image: node:22-bookworm-slim
    restart: on-failure
    working_dir: /opt/umbrel-frigate/app
    command: node server.js
    volumes:
      - ./app:/opt/umbrel-frigate/app:ro
      - ./web:/opt/umbrel-frigate/web:ro
      - ${APP_DATA_DIR}/data:/data
      - ${TOR_DATA_DIR}:/tor-data:ro
    environment:
      PORT: "2107"
      DEVICE_DOMAIN_NAME: "${DEVICE_DOMAIN_NAME}"
      FRIGATE_NETWORK: "${APP_BITCOIN_NETWORK}"
      FRIGATE_TCP_PORT: "${APP_ALBERCOIN_STORE_FRIGATE_NODE_PORT}"
      FRIGATE_HIDDEN_SERVICE_FILE: "/tor-data/app-albercoin-store-frigate-frigate/hostname"
      BITCOIN_RPC_HOST: "${APP_BITCOIN_NODE_IP}"
      BITCOIN_RPC_PORT: "${APP_BITCOIN_RPC_PORT}"
      BITCOIN_RPC_USER: "${APP_BITCOIN_RPC_USER}"
      BITCOIN_RPC_PASS: "${APP_BITCOIN_RPC_PASS}"
      BITCOIN_ZMQ_SEQUENCE_ENDPOINT: "tcp://${APP_BITCOIN_NODE_IP}:${APP_BITCOIN_ZMQ_SEQUENCE_PORT}"
      ELECTRUM_BACKEND_SERVER: "tcp://${APP_ELECTRS_NODE_IP}:${APP_ELECTRS_NODE_PORT}"
    networks:
      default:
        ipv4_address: $APP_ALBERCOIN_STORE_FRIGATE_IP

  frigate:
    image: ghcr.io/remcoros/frigate-docker:latest
    restart: on-failure
    stop_grace_period: 2m
    entrypoint:
      - /bin/sh
      - -c
      - while [ ! -f /root/.frigate/start ]; do sleep 2; done; if [ "$${NETWORK}" = "mainnet" ] || [ "$${NETWORK}" = "bitcoin" ]; then exec /opt/frigate/bin/frigate -d /root/.frigate; else exec /opt/frigate/bin/frigate -n "$${NETWORK}" -d /root/.frigate; fi
    volumes:
      - ${APP_DATA_DIR}/data/frigate:/root/.frigate
      - ${APP_BITCOIN_DATA_DIR}:/bitcoin:ro
    ports:
      - "${APP_ALBERCOIN_STORE_FRIGATE_NODE_PORT}:${APP_ALBERCOIN_STORE_FRIGATE_NODE_PORT}"
    environment:
      NETWORK: "${APP_BITCOIN_NETWORK}"
    networks:
      default:
        ipv4_address: $APP_ALBERCOIN_STORE_FRIGATE_NODE_IP

  tor:
    image: getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ./torrc:/etc/tor/torrc:ro
      - ${TOR_DATA_DIR}:/data
    environment:
      HOME: "/tmp"
    networks:
      default:
        ipv4_address: $APP_ALBERCOIN_STORE_FRIGATE_TOR_PROXY_IP
