# IP ADDRESSES
export APP_ALBERCOIN_STORE_FRIGATE_IP="10.21.23.30"
export APP_ALBERCOIN_STORE_FRIGATE_TOR_PROXY_IP="10.21.23.31"
export APP_ALBERCOIN_STORE_FRIGATE_NODE_IP="10.21.23.32"

# PORTS
export APP_ALBERCOIN_STORE_FRIGATE_UI_PORT="2107"
export APP_ALBERCOIN_STORE_FRIGATE_NODE_PORT="57001"

# HIDDEN SERVICE
frigate_hidden_service_file="${EXPORTS_TOR_DATA_DIR}/app-${EXPORTS_APP_ID}-frigate/hostname"
export APP_ALBERCOIN_STORE_FRIGATE_HIDDEN_SERVICE="$(cat "${frigate_hidden_service_file}" 2>/dev/null || echo "notyetset.onion")"
