#!/usr/bin/env python3
import html, json, os, re, socket, urllib.parse
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path

DATA_DIR = Path(os.environ.get("FRIGATE_DATA_DIR", "/data"))
SETTINGS_FILE = DATA_DIR / "frigate-settings.json"
CONFIG_DIR = DATA_DIR / "frigate-home"
CONFIG_FILE = CONFIG_DIR / "config.toml"
LOG_FILE = DATA_DIR / "frigate.log"
CONTAINER_NAME = os.environ.get("FRIGATE_SERVER_CONTAINER", "albercoin-store-frigate_server_1")
DOCKER_SOCK = os.environ.get("DOCKER_SOCK", "/var/run/docker.sock")

DEFAULTS = {
    "profile": "balanced",
    "cacheSize": "2M",
    "computeBackend": "CPU",
    "dbThreads": "2",
    "memoryLimit": "3GB",
    "batchSize": "100000",
    "rpcBatchSize": "50",
    "rpcRequestTimeoutSeconds": "120",
    "maxLabels": "10",
    "maxSubscriptions": "100",
    "tcpPort": "57001",
}

PRESETS = {
    "low": {"cacheSize":"1M", "computeBackend":"CPU", "dbThreads":"1", "memoryLimit":"2GB", "batchSize":"50000", "rpcBatchSize":"25", "rpcRequestTimeoutSeconds":"180", "maxLabels":"5", "maxSubscriptions":"25"},
    "balanced": {"cacheSize":"2M", "computeBackend":"CPU", "dbThreads":"2", "memoryLimit":"3GB", "batchSize":"100000", "rpcBatchSize":"50", "rpcRequestTimeoutSeconds":"120", "maxLabels":"10", "maxSubscriptions":"100"},
    "fast": {"cacheSize":"5M", "computeBackend":"AUTO", "dbThreads":"4", "memoryLimit":"6GB", "batchSize":"300000", "rpcBatchSize":"100", "rpcRequestTimeoutSeconds":"120", "maxLabels":"10", "maxSubscriptions":"150"},
    "max": {"cacheSize":"10M", "computeBackend":"AUTO", "dbThreads":"6", "memoryLimit":"8GB", "batchSize":"300000", "rpcBatchSize":"100", "rpcRequestTimeoutSeconds":"180", "maxLabels":"20", "maxSubscriptions":"250"},
}

FIELDS = list(DEFAULTS.keys())


def env(name, default=""):
    return os.environ.get(name, default)


def load_settings():
    data = DEFAULTS.copy()
    if SETTINGS_FILE.exists():
        try:
            data.update(json.loads(SETTINGS_FILE.read_text()))
        except Exception:
            pass
    return data


def validate(data):
    errors = []
    if data.get("computeBackend") not in ("AUTO", "GPU", "CPU"):
        errors.append("computeBackend debe ser AUTO, GPU o CPU")
    patterns = {
        "cacheSize": r"^[1-9][0-9]*[KMG]$",
        "memoryLimit": r"^[1-9][0-9]*(MB|GB)$",
        "dbThreads": r"^[1-9][0-9]?$",
        "batchSize": r"^[1-9][0-9]{3,8}$",
        "rpcBatchSize": r"^[1-9][0-9]{0,3}$",
        "rpcRequestTimeoutSeconds": r"^[1-9][0-9]{0,4}$",
        "maxLabels": r"^[1-9][0-9]{0,3}$",
        "maxSubscriptions": r"^[1-9][0-9]{0,4}$",
        "tcpPort": r"^[1-9][0-9]{1,4}$",
    }
    for key, pattern in patterns.items():
        if not re.match(pattern, str(data.get(key, ""))):
            errors.append(f"{key} tiene formato inválido")
    port = int(data.get("tcpPort", 0)) if str(data.get("tcpPort", "")).isdigit() else 0
    if not 1 <= port <= 65535:
        errors.append("tcpPort fuera de rango")
    return errors


def render_toml(data):
    bitcoin_ip = env("APP_BITCOIN_NODE_IP", "bitcoin")
    rpc_port = env("APP_BITCOIN_RPC_PORT", "8332")
    zmq_port = env("APP_BITCOIN_ZMQ_SEQUENCE_PORT", "28336")
    electrs_ip = env("APP_ELECTRS_NODE_IP", "electrs")
    electrs_port = env("APP_ELECTRS_NODE_PORT", "50001")
    network = env("FRIGATE_NETWORK", env("APP_BITCOIN_NETWORK", "mainnet"))
    return f'''# Frigate configuration generated by Umbrel config panel. Do not edit while Frigate is running.
# Network: {network}

[core]
connect = true
server = "http://{bitcoin_ip}:{rpc_port}"
authType = "COOKIE"
dataDir = "/data/.bitcoin"
zmqSequenceEndpoint = "tcp://{bitcoin_ip}:{zmq_port}"
rpcRequestTimeoutSeconds = {int(data["rpcRequestTimeoutSeconds"])}
rpcBatchSize = {int(data["rpcBatchSize"])}

[index]
cacheSize = "{data["cacheSize"]}"

[scan]
batchSize = {int(data["batchSize"])}
computeBackend = "{data["computeBackend"]}"
dbThreads = {int(data["dbThreads"])}
memoryLimit = "{data["memoryLimit"]}"
maxLabels = {int(data["maxLabels"])}
maxSubscriptions = {int(data["maxSubscriptions"])}

[server]
tcp = "tcp://0.0.0.0:{int(data["tcpPort"])}"
backendElectrumServer = "tcp://{electrs_ip}:{electrs_port}"
'''


def save_settings(data):
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    SETTINGS_FILE.write_text(json.dumps(data, indent=2, sort_keys=True))
    CONFIG_FILE.write_text(render_toml(data))
    LOG_FILE.touch(exist_ok=True)


def docker(method, path):
    req = f"{method} {path} HTTP/1.1\r\nHost: docker\r\nContent-Length: 0\r\nConnection: close\r\n\r\n".encode()
    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    s.settimeout(10)
    s.connect(DOCKER_SOCK)
    s.sendall(req)
    chunks = []
    while True:
        b = s.recv(4096)
        if not b:
            break
        chunks.append(b)
    s.close()
    raw = b"".join(chunks).decode("utf-8", "replace")
    status = raw.split("\r\n", 1)[0]
    return status


def docker_action(action):
    name = urllib.parse.quote(CONTAINER_NAME, safe="")
    if action == "restart":
        return docker("POST", f"/containers/{name}/restart?t=60")
    if action == "stop":
        return docker("POST", f"/containers/{name}/stop?t=60")
    if action == "start":
        return docker("POST", f"/containers/{name}/start")
    return "HTTP/1.1 400 Bad action"


def tail(path, lines=120):
    try:
        data = path.read_text(errors="replace").splitlines()[-lines:]
        return "\n".join(data)
    except Exception as e:
        return f"No se puede leer el log: {e}"


class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path.startswith("/config.toml"):
            self.send_text(CONFIG_FILE.read_text() if CONFIG_FILE.exists() else "", "text/plain")
            return
        self.page(load_settings(), "")

    def do_POST(self):
        length = int(self.headers.get("Content-Length", "0"))
        form = urllib.parse.parse_qs(self.rfile.read(length).decode())
        action = form.get("action", [""])[0]
        data = load_settings()
        if action == "preset":
            preset = form.get("profile", ["balanced"])[0]
            data.update(PRESETS.get(preset, PRESETS["balanced"]))
            data["profile"] = preset
            save_settings(data)
            self.page(data, f"Perfil {preset} aplicado. Reinicia Frigate para usarlo.")
            return
        if action in ("restart", "stop", "start"):
            try:
                result = docker_action(action)
            except Exception as e:
                result = f"ERROR Docker: {e}"
            self.page(data, result)
            return
        if action == "save_restart" or action == "save":
            for key in FIELDS:
                if key in form:
                    data[key] = form[key][0].strip()
            errors = validate(data)
            if errors:
                self.page(data, " | ".join(errors))
                return
            save_settings(data)
            msg = "Configuración guardada."
            if action == "save_restart":
                try:
                    msg += " " + docker_action("restart")
                except Exception as e:
                    msg += f" ERROR Docker: {e}"
            self.page(data, msg)
            return
        self.page(data, "Acción no válida")

    def send_text(self, content, ctype="text/html"):
        body = content.encode()
        self.send_response(200)
        self.send_header("Content-Type", ctype + "; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def page(self, data, msg):
        def v(k): return html.escape(str(data.get(k, "")))
        log = html.escape(tail(LOG_FILE))
        cfg = html.escape(CONFIG_FILE.read_text() if CONFIG_FILE.exists() else "")
        html_body = f'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Frigate Config</title>
<style>body{{font-family:system-ui,-apple-system,Segoe UI,sans-serif;background:#101114;color:#eee;margin:0}}main{{max-width:1040px;margin:auto;padding:24px}}.card{{background:#181a20;border:1px solid #2b2e38;border-radius:16px;padding:18px;margin:14px 0}}label{{display:block;margin:12px 0 6px;color:#cfd3dc}}input,select{{width:100%;padding:10px;border-radius:10px;border:1px solid #3b3f4a;background:#0d0e12;color:#fff}}button{{padding:10px 14px;border:0;border-radius:10px;margin:6px 6px 6px 0;cursor:pointer}}.primary{{background:#68d391;color:#07140b;font-weight:700}}.danger{{background:#fc8181;color:#210606}}.muted{{background:#2d3748;color:#fff}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}}pre{{white-space:pre-wrap;overflow:auto;background:#0d0e12;padding:12px;border-radius:12px;max-height:360px}}.msg{{color:#90cdf4;font-weight:700}}</style></head><body><main>
<h1>Frigate Umbrel · rendimiento</h1><p>Edita parámetros, guarda y reinicia solo el servicio <code>server</code>.</p><p class="msg">{html.escape(msg)}</p>
<div class="card"><h2>Perfiles rápidos</h2><form method="post"><input type="hidden" name="action" value="preset"><select name="profile"><option value="low">Bajo consumo</option><option value="balanced">Equilibrado</option><option value="fast">Rápido</option><option value="max">Máximo rendimiento</option></select><button class="muted">Aplicar perfil</button></form></div>
<form method="post" class="card"><h2>Configuración manual</h2><div class="grid">
<div><label>cacheSize</label><input name="cacheSize" value="{v('cacheSize')}"><small>1M-2M baja RAM, 5M-10M rápido.</small></div>
<div><label>computeBackend</label><select name="computeBackend"><option {'selected' if data.get('computeBackend')=='CPU' else ''}>CPU</option><option {'selected' if data.get('computeBackend')=='AUTO' else ''}>AUTO</option><option {'selected' if data.get('computeBackend')=='GPU' else ''}>GPU</option></select></div>
<div><label>dbThreads</label><input name="dbThreads" value="{v('dbThreads')}"></div>
<div><label>memoryLimit</label><input name="memoryLimit" value="{v('memoryLimit')}"></div>
<div><label>batchSize</label><input name="batchSize" value="{v('batchSize')}"></div>
<div><label>rpcBatchSize</label><input name="rpcBatchSize" value="{v('rpcBatchSize')}"></div>
<div><label>rpcRequestTimeoutSeconds</label><input name="rpcRequestTimeoutSeconds" value="{v('rpcRequestTimeoutSeconds')}"></div>
<div><label>maxLabels</label><input name="maxLabels" value="{v('maxLabels')}"></div>
<div><label>maxSubscriptions</label><input name="maxSubscriptions" value="{v('maxSubscriptions')}"></div>
<div><label>tcpPort</label><input name="tcpPort" value="{v('tcpPort')}"></div>
</div><br><button class="muted" name="action" value="save">Guardar</button><button class="primary" name="action" value="save_restart">Guardar y reiniciar Frigate</button></form>
<div class="card"><h2>Servicio</h2><form method="post"><button class="primary" name="action" value="restart">Reiniciar server</button><button class="danger" name="action" value="stop">Parar server</button><button class="muted" name="action" value="start">Arrancar server</button></form></div>
<div class="card"><h2>config.toml generado</h2><pre>{cfg}</pre></div><div class="card"><h2>Últimas líneas de frigate.log</h2><pre>{log}</pre></div>
</main></body></html>'''
        self.send_text(html_body)

if __name__ == "__main__":
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    if not SETTINGS_FILE.exists() or not CONFIG_FILE.exists():
        save_settings(load_settings())
    HTTPServer(("0.0.0.0", 8080), Handler).serve_forever()
