server {
    listen 8080;

    location = /favicon.ico {
        root /usr/share/nginx/html;
        try_files /icon.png =404;
    }

    location /api/ {
        proxy_pass http://api:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 10s;
        proxy_connect_timeout 5s;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ =404;
    }
}
